"use client";

import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Search, FolderOpen, Calendar, Globe } from "lucide-react";
import { Input } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";
import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Skeleton } from "@/components/ui/Skeleton";
import { api } from "@/lib/api";

interface Project {
  _id: string;
  title: string;
  category: string;
  description: string;
  tagline: string;
  visibility: string;
  createdAt: string;
}

export default function ExplorePage() {
  const [searchTerm, setSearchTerm] = useState('');

  const { data: projects, isLoading, error } = useQuery({
    queryKey: ['public-projects'],
    queryFn: async () => {
      const res = await api.get('/projects/public');
      return res.data.data as Project[];
    }
  });

  const filteredProjects = projects?.filter(p => 
    p.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.category.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="min-h-screen pt-8 pb-24">
      <div className="container mx-auto px-4">
        <div className="mb-10 text-center max-w-2xl mx-auto">
          <h1 className="text-4xl font-bold mb-4 flex justify-center items-center gap-3">
            <Globe className="w-10 h-10 text-blue-500" />
            Explore AI Generated Projects
          </h1>
          <p className="text-text-muted text-lg">Browse public product roadmaps, requirements, and user stories generated by the community using ProductPilot AI.</p>
        </div>

        {/* Search & Filters */}
        <div className="flex flex-col md:flex-row gap-4 mb-12 max-w-3xl mx-auto">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-text-muted" />
            <Input 
              type="text" 
              placeholder="Search for projects, industries, or keywords..." 
              className="pl-10 h-12 text-base"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          <Button size="lg" className="h-12 px-8">Search</Button>
        </div>

        {/* Loading State */}
        {isLoading && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
            {[...Array(6)].map((_, i) => (
              <Card key={i} className="h-[200px]">
                <CardHeader>
                  <Skeleton className="h-6 w-3/4 mb-2" />
                  <Skeleton className="h-4 w-1/4 mb-4" />
                  <Skeleton className="h-16 w-full" />
                </CardHeader>
              </Card>
            ))}
          </div>
        )}

        {/* Error State */}
        {error && (
          <div className="text-center p-8 bg-error/10 border border-error/20 rounded-xl max-w-2xl mx-auto text-error">
            Failed to load public projects. Please try again later.
          </div>
        )}

        {/* Results Grid */}
        {!isLoading && !error && filteredProjects && filteredProjects.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
            {filteredProjects.map((project) => (
              <Card key={project._id} className="hover:border-primary/30 transition-colors group">
                <CardHeader>
                  <CardTitle className="flex justify-between items-start">
                    <span className="group-hover:text-primary transition-colors line-clamp-1">{project.title}</span>
                  </CardTitle>
                  <CardDescription className="flex items-center gap-2">
                    <Badge variant="default">{project.category}</Badge>
                  </CardDescription>
                  <div className="pt-4 flex flex-col gap-3 flex-grow">
                    <p className="text-sm text-text-muted line-clamp-2">
                      {project.tagline || project.description || "No description provided."}
                    </p>
                    <div className="flex items-center text-xs text-text-muted mt-auto pt-4 border-t border-border">
                      <Calendar className="w-3.5 h-3.5 mr-1.5" />
                      {new Date(project.createdAt).toLocaleDateString()}
                    </div>
                  </div>
                </CardHeader>
              </Card>
            ))}
          </div>
        )}

        {/* Empty State */}
        {!isLoading && !error && (!filteredProjects || filteredProjects.length === 0) && (
          <div className="bg-surface border border-border rounded-[16px] p-16 text-center max-w-4xl mx-auto flex flex-col items-center">
            <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mb-6">
              <FolderOpen className="w-10 h-10 text-primary" />
            </div>
            <h2 className="text-2xl font-bold mb-3">No public projects found</h2>
            <p className="text-text-muted mb-8 max-w-md">
              {searchTerm ? "No projects match your search criteria." : "The community hasn't published any projects yet. Be the first to create and publish a project with our AI agents!"}
            </p>
            {!searchTerm && (
              <Button variant="primary" size="lg">Create Your First Project</Button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
