"use client";
import { useQuery } from '@tanstack/react-query';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card';
import { useAuthStore } from '@/store/useAuthStore';
import { FolderKanban, Sparkles, Code2, Users } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { api } from '@/lib/api';
import { Skeleton } from '@/components/ui/Skeleton';

interface DashboardData {
  stats: {
    activeProjects: number;
    aiDocumentsGenerated: number;
    userStories: number;
    teamMembers: number;
  };
  chartData: {
    name: string;
    usage: number;
  }[];
  recentActivity: {
    action: string;
    project: string;
    time: string;
  }[];
}

export default function DashboardHome() {
  const user = useAuthStore((state) => state.user);

  const { data: dashboardData, isLoading, error } = useQuery({
    queryKey: ['dashboardData'],
    queryFn: async () => {
      const res = await api.get('/dashboard');
      return res.data.data as DashboardData;
    }
  });

  const stats = [
    { title: 'Active Projects', value: dashboardData?.stats.activeProjects || 0, icon: FolderKanban, color: 'text-primary' },
    { title: 'AI Documents Generated', value: dashboardData?.stats.aiDocumentsGenerated || 0, icon: Sparkles, color: 'text-secondary' },
    { title: 'User Stories', value: dashboardData?.stats.userStories || 0, icon: Code2, color: 'text-accent' },
    { title: 'Team Members', value: dashboardData?.stats.teamMembers || 0, icon: Users, color: 'text-info' },
  ];

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700 ease-out">
      <div>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Welcome back, {user?.name || 'Builder'}</h1>
        <p className="text-text-muted">Here is an overview of your product development progress.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {isLoading ? (
          Array.from({ length: 4 }).map((_, i) => (
            <Card key={i}>
              <CardContent className="p-6 flex items-center justify-between">
                <div>
                  <Skeleton className="w-24 h-4 mb-2" />
                  <Skeleton className="w-12 h-8" />
                </div>
                <Skeleton className="w-12 h-12 rounded-xl" />
              </CardContent>
            </Card>
          ))
        ) : (
          stats.map((stat, i) => {
            const Icon = stat.icon;
            return (
              <Card key={i}>
                <CardContent className="p-6 flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-text-muted mb-1">{stat.title}</p>
                    <h3 className="text-3xl font-bold">{stat.value}</h3>
                  </div>
                  <div className={`p-3 rounded-xl bg-surface-hover border border-border ${stat.color}`}>
                    <Icon className="w-6 h-6" />
                  </div>
                </CardContent>
              </Card>
            );
          })
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>AI Agent Usage</CardTitle>
            <CardDescription>Tokens generated by ProductPilot AI over the last 7 days.</CardDescription>
          </CardHeader>
          <CardContent className="h-[300px] w-full">
            {isLoading ? (
              <Skeleton className="w-full h-full rounded-xl" />
            ) : dashboardData?.chartData ? (
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={dashboardData.chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#27272a" vertical={false} />
                  <XAxis dataKey="name" stroke="#a1a1aa" fontSize={12} tickLine={false} axisLine={false} dy={10} />
                  <YAxis stroke="#a1a1aa" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(val) => val === 0 ? '' : val} />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: '8px' }}
                    itemStyle={{ color: '#f3f4f6' }}
                  />
                  <Line 
                    type="monotone" 
                    dataKey="usage" 
                    stroke="#2563EB" 
                    strokeWidth={3}
                    dot={{ r: 4, fill: '#2563EB', strokeWidth: 0 }}
                    activeDot={{ r: 6, fill: '#4F46E5', strokeWidth: 0 }}
                    animationDuration={1500}
                  />
                </LineChart>
              </ResponsiveContainer>
            ) : (
              <div className="w-full h-full flex items-center justify-center text-text-muted">
                No data available
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
            <CardDescription>Your latest project updates.</CardDescription>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="space-y-4">
                {[1, 2, 3].map(i => (
                  <div key={i} className="flex gap-4">
                    <Skeleton className="w-2 h-2 rounded-full mt-2" />
                    <div className="flex-1">
                      <Skeleton className="w-full h-4 mb-2" />
                      <Skeleton className="w-2/3 h-3" />
                    </div>
                  </div>
                ))}
              </div>
            ) : dashboardData?.recentActivity?.length ? (
              <div className="space-y-4">
                {dashboardData.recentActivity.map((activity, i) => (
                  <div key={i} className="flex items-start gap-4">
                    <div className="w-2 h-2 rounded-full bg-primary mt-2 flex-shrink-0"></div>
                    <div>
                      <p className="text-sm font-medium">{activity.action}</p>
                      <p className="text-xs text-text-muted">
                        {activity.project} • {new Date(activity.time).toLocaleDateString()}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-8 text-text-muted">
                No recent activity found.
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
