"use client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card';
import { useAuthStore } from '@/store/useAuthStore';
import { FolderKanban, Sparkles, Code2, Users } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const mockChartData = [
  { name: 'Mon', usage: 12 },
  { name: 'Tue', usage: 19 },
  { name: 'Wed', usage: 15 },
  { name: 'Thu', usage: 22 },
  { name: 'Fri', usage: 28 },
  { name: 'Sat', usage: 10 },
  { name: 'Sun', usage: 35 },
];

export default function DashboardHome() {
  const user = useAuthStore((state) => state.user);

  const stats = [
    { title: 'Active Projects', value: '3', icon: FolderKanban, color: 'text-primary' },
    { title: 'AI Documents Generated', value: '24', icon: Sparkles, color: 'text-secondary' },
    { title: 'User Stories', value: '142', icon: Code2, color: 'text-accent' },
    { title: 'Team Members', value: '1', icon: Users, color: 'text-info' },
  ];

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Welcome back, {user?.name || 'Builder'}</h1>
        <p className="text-text-muted">Here is an overview of your product development progress.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => {
          const Icon = stat.icon;
          return (
            <Card key={i}>
              <CardContent className="p-6 flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-text-muted mb-1">{stat.title}</p>
                  <h3 className="text-3xl font-bold">{stat.value}</h3>
                </div>
                <div className={`p-3 rounded-xl bg-surface-hover border border-border ${stat.color}`}>
                  <Icon className="w-6 h-6" />
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>AI Agent Usage</CardTitle>
            <CardDescription>Tokens generated by ProductPilot AI over the last 7 days.</CardDescription>
          </CardHeader>
          <CardContent className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={mockChartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#27272a" />
                <XAxis dataKey="name" stroke="#a1a1aa" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#a1a1aa" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#18181b', borderColor: '#27272a', borderRadius: '8px' }}
                  itemStyle={{ color: '#f3f4f6' }}
                />
                <Line 
                  type="monotone" 
                  dataKey="usage" 
                  stroke="#2563EB" 
                  strokeWidth={3}
                  dot={{ r: 4, fill: '#2563EB', strokeWidth: 0 }}
                  activeDot={{ r: 6, fill: '#4F46E5', strokeWidth: 0 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
            <CardDescription>Your latest project updates.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {[
                { action: 'Generated PRD', project: 'E-commerce App', time: '2 hours ago' },
                { action: 'Created User Stories', project: 'SaaS Platform', time: '5 hours ago' },
                { action: 'Created Project', project: 'Fitness Tracker', time: '1 day ago' },
              ].map((activity, i) => (
                <div key={i} className="flex items-start gap-4">
                  <div className="w-2 h-2 rounded-full bg-primary mt-2"></div>
                  <div>
                    <p className="text-sm font-medium">{activity.action}</p>
                    <p className="text-xs text-text-muted">{activity.project} • {activity.time}</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
